server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 将 /api 请求代理到后端服务（容器内部 svc 地址）
    location /blog-api/ {
        proxy_pass http://blog-api:8080/blog-api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}