server {
    listen 80;
    server_name blog.kcbjt.com; # 关键：通过域名匹配

    location / {
        # 将所有请求直接代理到项目 A 的容器
        proxy_pass http://blog-view:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    # 后端 API 访问（路径前缀 /api）
    location /blog-api/ {
        proxy_pass http://blog-api:8080/blog-api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    server_name admin.blog.kcbjt.com; # 关键：通过域名匹配

    location / {
        # 将所有请求直接代理到项目 B 的容器
        proxy_pass http://blog-cms:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    # 后端 API 访问（路径前缀 /api）
    location /blog-api/ {
        proxy_pass http://blog-api:8080/blog-api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}